# Generated by Django 4.2 on 2023-04-18 15:36

from django.db import migrations, models


def create_animals(apps, schema_editor):
    Weather = apps.get_model("is_it_raining", "Weather")
    Animal = apps.get_model("is_it_raining", "Animal")

    # animal names and their weather codes
    animal_data = [
        {'name': 'Alligator', 'weather_code': 2},
        {'name': 'Toad', 'weather_code': 3},
        {'name': 'Megalodon', 'weather_code': 5},
        {'name': 'Goat', 'weather_code': 6},
        {'name': 'Trex', 'weather_code': 7},
        {'name': 'Toucan', 'weather_code': 8},
        {'name': 'Stegosaurus', 'weather_code': 8},
    ]

    for animal in animal_data:
        Animal.objects.get_or_create(
            name=animal['name']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0005_remove_animal_owner'),
    ]

    operations = [
    ]
