# Generated by Django 4.2 on 2023-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=3)),
                ('description', models.CharField()),
                ('icon', models.CharField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
