# Generated by Django 4.2 on 2023-04-17 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0002_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temperature',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals_of_owner', to=settings.AUTH_USER_MODEL)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_type_for_animal', to='is_it_raining.weather')),
            ],
        ),
    ]
