# Generated by Django 4.2 on 2023-04-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0005_remove_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
