# Generated by Django 4.2 on 2023-04-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0008_alter_animal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='is_it_raining.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='capturedanimal',
            constraint=models.UniqueConstraint(fields=('owner', 'animal'), name='unique_ownership'),
        ),
    ]
