# Generated by Django 4.2 on 2023-04-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0010_remove_animal_image_animalimage'),
        ('is_it_raining', '0010_trade'),
    ]

    operations = [
    ]
