# Generated by Django 4.2 on 2023-04-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0013_weathericon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathericon',
            old_name='image',
            new_name='icon_image',
        ),
        migrations.AddField(
            model_name='weathericon',
            name='icon_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
