# Generated by Django 4.2 on 2023-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0014_rename_image_weathericon_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathericon',
            name='is_day',
            field=models.BooleanField(null=True),
        ),
    ]
