# Generated by Django 4.2 on 2023-04-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0015_trade_status'),
        ('is_it_raining', '0015_weathericon_is_day'),
    ]

    operations = [
    ]
