# Generated by Django 4.2 on 2023-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0016_merge_0015_trade_status_0015_weathericon_is_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background')),
                ('code', models.CharField(max_length=3)),
                ('day_or_night', models.CharField(max_length=2)),
            ],
        ),
    ]
