# Generated by Django 4.2 on 2023-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0017_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team-fries-images'),
        ),
        migrations.DeleteModel(
            name='AnimalImage',
        ),
    ]
