# Generated by Django 4.2 on 2023-04-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0018_animal_image_delete_animalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='varation_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='pending', max_length=20),
        ),
    ]
