# Generated by Django 4.2 on 2023-04-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0020_rename_varation_type_animal_variation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='variation_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=20),
        ),
    ]
