# Generated by Django 4.2 on 2023-04-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0021_alter_animal_variation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherIcon',
        ),
    ]
