# Generated by Django 4.2 on 2023-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0022_delete_weathericon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capturedanimal',
            name='unique_ownership',
        ),
        migrations.AddConstraint(
            model_name='capturedanimal',
            constraint=models.UniqueConstraint(
                fields=('owner', 'animal'), name='unique_ownership'),
        ),
    ]
