# Generated by Django 4.2 on 2023-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0023_remove_capturedanimal_unique_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capturedanimal',
            name='unique_ownership',
        ),
        migrations.AddConstraint(
            model_name='capturedanimal',
            constraint=models.UniqueConstraint(fields=('owner', 'animal'), name='unique_ownership'),
        ),
    ]
