# Generated by Django 4.2 on 2023-04-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0024_remove_capturedanimal_unique_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capturedanimal',
            name='unique_ownership',
        ),
    ]
