# Generated by Django 4.2 on 2023-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0028_capturedanimal_capture_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedanimal',
            name='captured_date',
        ),
        migrations.AlterField(
            model_name='capturedanimal',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
