# Generated by Django 4.2 on 2023-04-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0027_remove_capturedanimal_unique_ownership_and_more'),
        ('is_it_raining', '0029_remove_capturedanimal_captured_date_and_more'),
    ]

    operations = [
    ]
