# Generated by Django 4.2 on 2023-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0030_merge_20230428_1647'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='capturedanimal',
            constraint=models.UniqueConstraint(fields=('owner', 'animal'), name='unique_ownership'),
        ),
    ]
