# Generated by Django 4.2 on 2023-04-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0030_specialanimal_capturedspecialanimal'),
        ('is_it_raining', '0031_capturedanimal_unique_ownership'),
    ]

    operations = [
    ]
