# Generated by Django 4.2 on 2023-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0032_merge_20230428_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
