# Generated by Django 4.2 on 2023-04-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_it_raining', '0033_background_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='audio_file',
        ),
    ]
